import "./globals.css";
import styles from "./layout.module.css";
import { Noto_Sans } from "next/font/google";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
});

export const metadata = {
  title: "Ömer Serdar ŞERİFOĞLU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className={`${styles.body} ${notoSans.className}`}>
        <div className={styles.topbar}>TOP</div>
        <main className={styles.main}>{children}</main>
        <div className={styles.sidemenu}>Side</div>
      </body>
    </html>
  );
}
